"""
The revision a build script stamps into `--version` must describe the source it built.

Both `crates/fdu/build.rs` and `crates/fdu-core/build.rs` carry `emit_version`, kept in
step by hand (fdu-zuyq). A maturin sdist carries no `.cargo_vcs_info.json`, so when pip or
uv unpacked one inside an unrelated git checkout, the enclosing repository's HEAD became
`fdu --version`, and every installed skill's "Generated by" line with it (fdu-h2bj).
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = (ROOT / "crates" / "fdu" / "build.rs", ROOT / "crates" / "fdu-core" / "build.rs")
SEMVER = "9.9.9"


def emit_version(path: Path) -> str:
    """The text of one script's `emit_version`, from its signature to its closing brace."""
    match = re.search(r"(?ms)^fn emit_version\(\) \{\n.*?^\}\n", path.read_text(encoding="utf-8"))
    if match is None:
        raise AssertionError(f"{path} has no emit_version")
    return match.group(0)


def git(directory: Path, *arguments: str) -> str:
    """Run git in `directory` without the invoking user's configuration."""
    command = ["git", "-c", "user.name=fdu", "-c", "user.email=fdu@example.invalid"]
    command += ["-c", "commit.gpgsign=false", *arguments]
    return subprocess.run(
        command, cwd=directory, check=True, capture_output=True, text=True, env=git_env()
    ).stdout.strip()


def git_env() -> dict[str, str]:
    env = {
        key: value
        for key, value in os.environ.items()
        if not key.startswith("GIT_") and key != "FDU_RELEASE_TAG"
    }
    env["GIT_CONFIG_GLOBAL"] = os.devnull
    env["GIT_CONFIG_NOSYSTEM"] = "1"
    return env


class EmitVersionTests(unittest.TestCase):
    def test_both_copies_stay_in_step(self) -> None:
        self.assertEqual(emit_version(SCRIPTS[0]), emit_version(SCRIPTS[1]))

    @unittest.skipUnless(shutil.which("rustc") and shutil.which("git"), "needs rustc and git")
    def test_only_a_repository_that_tracks_the_package_names_its_revision(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            base = Path(temporary).resolve()
            script = base / "emit-version"
            # From the checkout, so rust-toolchain.toml picks the pinned compiler.
            subprocess.run(
                ["rustc", "--edition", "2024", str(SCRIPTS[0]), "-o", str(script)],
                cwd=ROOT,
                check=True,
                capture_output=True,
            )

            def stamped(package: Path) -> str:
                env = git_env()
                # Nothing above the scratch directory may answer for it.
                env["GIT_CEILING_DIRECTORIES"] = str(base)
                env["CARGO_PKG_VERSION"] = SEMVER
                output = subprocess.run(
                    [str(script)], cwd=package, check=True, capture_output=True, text=True, env=env
                ).stdout
                values = re.findall(r"^cargo:rustc-env=FDU_BUILD_VERSION=(.*)$", output, re.M)
                self.assertEqual(len(values), 1, output)
                return values[0]

            def package_in(directory: Path) -> Path:
                package = directory / "crates" / "fdu"
                package.mkdir(parents=True)
                shutil.copy(ROOT / "crates" / "fdu" / "Cargo.toml", package / "Cargo.toml")
                return package

            # An sdist unpacked, untracked, inside somebody else's repository.
            foreign = base / "foreign"
            foreign.mkdir()
            git(foreign, "init", "-q")
            git(foreign, "commit", "-q", "--allow-empty", "-m", "unrelated")
            self.assertEqual(stamped(package_in(foreign / "fdu-9.9.9")), SEMVER)

            # No repository at all.
            self.assertEqual(stamped(package_in(base / "plain")), SEMVER)

            # A checkout that tracks the package still carries its revision.
            own = base / "own"
            own.mkdir()
            package = package_in(own)
            git(own, "init", "-q")
            git(own, "add", ".")
            git(own, "commit", "-q", "-m", "fdu")
            revision = git(own, "rev-parse", "--short=9", "HEAD")
            self.assertEqual(stamped(package), f"{SEMVER}-dev+g{revision}")


if __name__ == "__main__":
    unittest.main()
