"""Typed Python interface to fdu's retained file roll-up engine."""

from __future__ import annotations

from ._api import (
    FduError,
    FilesystemError,
    Index,
    InvalidArgumentError,
    Watch,
    cache_path,
    cache_status,
    clear_all_caches,
    clear_cache,
    list_caches,
    open,
    scan,
)
from ._api import (
    _main as _main,
)
from ._models import (
    AnalysisMetadata,
    AnalysisOptions,
    AnalysisProfile,
    Analyzer,
    Bound,
    CachePolicy,
    CacheStatus,
    Change,
    ChangeKind,
    ChangeSet,
    Child,
    Coverage,
    Detection,
    EntryKind,
    ExtensionRow,
    ExtensionsSection,
    ExtensionTally,
    FileRow,
    FilesSection,
    Freshness,
    MetricRow,
    MetricShare,
    MetricsSection,
    MetricValues,
    OperationError,
    Provenance,
    Query,
    RefreshResult,
    Report,
    ReportSection,
    ReportSource,
    RollUp,
    ScanOptions,
    Selection,
    SizeMetric,
    SortKey,
    Status,
    SummaryRow,
    SummarySection,
    TreeNode,
    TreeSection,
    ValueSource,
    View,
    WatchOptions,
)
from ._native import __version__

__all__ = [
    "AnalysisMetadata",
    "AnalysisOptions",
    "AnalysisProfile",
    "Analyzer",
    "Bound",
    "CachePolicy",
    "CacheStatus",
    "Change",
    "ChangeKind",
    "ChangeSet",
    "Child",
    "Coverage",
    "Detection",
    "EntryKind",
    "ExtensionRow",
    "ExtensionTally",
    "ExtensionsSection",
    "FduError",
    "FileRow",
    "FilesSection",
    "FilesystemError",
    "Freshness",
    "Index",
    "InvalidArgumentError",
    "MetricRow",
    "MetricShare",
    "MetricValues",
    "MetricsSection",
    "OperationError",
    "Provenance",
    "Query",
    "RefreshResult",
    "Report",
    "ReportSection",
    "ReportSource",
    "RollUp",
    "ScanOptions",
    "Selection",
    "SizeMetric",
    "SortKey",
    "Status",
    "SummaryRow",
    "SummarySection",
    "TreeNode",
    "TreeSection",
    "ValueSource",
    "View",
    "Watch",
    "WatchOptions",
    "__version__",
    "cache_path",
    "cache_status",
    "clear_all_caches",
    "clear_cache",
    "list_caches",
    "open",
    "scan",
]

# Python 3.14 exposes the ``__future__.annotations`` feature object as a module
# global.  Keep it out of the intentionally small public package namespace.
globals().pop("annotations", None)
