"""Private native-extension contract used by the typed public facade."""

from collections.abc import Iterator
from os import PathLike
from typing import Any

__version__: str

class Index:
    @property
    def root(self) -> str: ...
    @property
    def clock(self) -> int: ...
    @property
    def complete(self) -> bool: ...
    @property
    def freshness(self) -> str: ...
    @property
    def errors(self) -> list[str]: ...
    @property
    def telemetry(self) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
    def status(self) -> dict[str, Any]: ...
    def report(self, **kwargs: object) -> dict[str, Any]: ...
    def report_handle(self, **kwargs: object) -> OneShot: ...
    def total(self, extensions: int | None = None, plane: str | None = None) -> dict[str, Any]: ...
    def rollup(
        self,
        path: str | PathLike[str],
        extensions: int | None = None,
        plane: str | None = None,
    ) -> dict[str, Any] | None: ...
    def children(
        self,
        path: str | PathLike[str] | None = None,
        after: str | None = None,
        limit: int | None = None,
        plane: str | None = None,
    ) -> dict[str, Any] | None: ...
    def read(
        self,
        children_of: str | PathLike[str] | None = None,
        rollups: list[str] | None = None,
        total: bool = False,
        extensions: int | None = None,
        after: str | None = None,
        limit: int | None = None,
        report: bool = False,
        views: list[str] | None = None,
        include: list[str] | None = None,
        exclude: list[str] | None = None,
        min_size: int | None = None,
        max_size: int | None = None,
        modified_since: str | None = None,
        modified_before: str | None = None,
        kind: str | None = None,
        tags: list[str] | None = None,
        not_tags: list[str] | None = None,
        plane: str | None = None,
        depth: str | None = None,
        limit_rows: str | None = None,
        sort: str | None = None,
        reverse: bool = False,
        size: str = "allocated",
        words_per_page: int = 250,
        as_of_ns: int | None = None,
        expected: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def provenance(self, path: str | PathLike[str] | None = None) -> dict[str, Any] | None: ...
    def refresh(self, path: str | PathLike[str] | None = None) -> dict[str, Any]: ...
    def cursor(self) -> dict[str, Any]: ...
    def since(self, cursor: dict[str, Any]) -> dict[str, Any]: ...
    def watch(self, **kwargs: object) -> Watch: ...

class TypeRegistry:
    @staticmethod
    def from_manifest(source: str, expect_fingerprint: int | None = None) -> TypeRegistry: ...
    @staticmethod
    def compiled() -> TypeRegistry: ...
    @property
    def fingerprint(self) -> int: ...
    @property
    def rule_count(self) -> int: ...
    @property
    def extension_count(self) -> int: ...
    @property
    def filename_count(self) -> int: ...
    def type_ids(self) -> list[str]: ...
    def classify(self, path: str | PathLike[str]) -> dict[str, Any]: ...

class Watch(Iterator[dict[str, Any]]):
    def __iter__(self) -> Watch: ...
    def report(self) -> OneShot: ...
    def __next__(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
    def __enter__(self) -> Watch: ...
    def __exit__(self, *args: object) -> bool: ...

def open(root: str | PathLike[str], **kwargs: object) -> Index: ...
def scan(root: str | PathLike[str], **kwargs: object) -> Index: ...
def cache_path(root: str | PathLike[str]) -> str | None: ...
def cache_status(root: str | PathLike[str]) -> dict[str, Any] | None: ...
def list_caches(root: str | PathLike[str]) -> list[dict[str, Any]]: ...
def render_cache_status(paths: list[str], format: str = ...) -> str: ...

class OneShot:
    def render(self, format: str, color: bool) -> str: ...
    def notes(self) -> list[str]: ...

def report_once(root: str | PathLike[str], **kwargs: object) -> OneShot: ...
def render_change(**kwargs: object) -> str: ...
def watch_rule(at_nanos: int) -> str: ...
def clear_cache(root: str | PathLike[str]) -> bool: ...
def clear_all_caches(root: str | PathLike[str]) -> int: ...
def main() -> int: ...
def contract() -> dict[str, list[str]]: ...
