"""Private native-extension contract used by the typed public facade."""

from collections.abc import Iterator
from os import PathLike
from typing import Any

__version__: str

class Index:
    @property
    def root(self) -> str: ...
    @property
    def clock(self) -> int: ...
    @property
    def complete(self) -> bool: ...
    @property
    def freshness(self) -> str: ...
    @property
    def errors(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def status(self) -> dict[str, Any]: ...
    def report(self, **kwargs: object) -> dict[str, Any]: ...
    def report_json(self, **kwargs: object) -> str: ...
    def total(self) -> dict[str, Any]: ...
    def rollup(self, path: str | PathLike[str]) -> dict[str, Any] | None: ...
    def children(self, path: str | PathLike[str] | None = None) -> list[dict[str, Any]] | None: ...
    def provenance(self, path: str | PathLike[str] | None = None) -> dict[str, Any] | None: ...
    def refresh(self) -> dict[str, Any]: ...
    def since(self, clock: int) -> dict[str, Any]: ...
    def watch(self, **kwargs: object) -> Watch: ...

class Watch(Iterator[list[dict[str, Any]]]):
    def __iter__(self) -> Watch: ...
    def __next__(self) -> list[dict[str, Any]]: ...
    def close(self) -> None: ...
    def __enter__(self) -> Watch: ...
    def __exit__(self, *args: object) -> bool: ...

def open(root: str | PathLike[str], **kwargs: object) -> Index: ...
def scan(root: str | PathLike[str], **kwargs: object) -> Index: ...
def cache_path(root: str | PathLike[str]) -> str | None: ...
def cache_status(root: str | PathLike[str]) -> dict[str, Any] | None: ...
def list_caches(root: str | PathLike[str]) -> list[dict[str, Any]]: ...
def render_cache_status(paths: list[str], format: str = ...) -> str: ...

class OneShot:
    def render(self, format: str, color: bool) -> str: ...

def report_once(root: str | PathLike[str], **kwargs: object) -> OneShot: ...
def clear_cache(root: str | PathLike[str]) -> bool: ...
def clear_all_caches(root: str | PathLike[str]) -> int: ...
def main() -> int: ...
def contract() -> dict[str, list[str]]: ...
