#!/usr/bin/env node
// Replay the golden corpus against the Python surface and compare what differs to a
// committed artifact.
//
// The corpus is not duplicated and no expected output is written twice.
// tests/golden/*.tryscript.md stays exactly as it is -- the Rust CLI's recorded output.
// This run points the same sessions at the Python shim and captures the differences
// into tests/parity/deviations-python.diff, which is reviewed like any golden and is
// the specification of how the two surfaces legitimately differ.
//
// The safety property is inverted on purpose. A naive parity run treats "no differences"
// as success, which is exactly what a fallthrough to the real binary produces -- the
// most dangerous failure would look like the best outcome. The committed artifact is
// non-empty by construction, because the shim names itself in --version. An empty
// result means the shim never ran, and that fails.

import { spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const artifact = join(root, 'tests', 'parity', 'deviations-python.diff');
const golden = join(root, 'tests', 'golden');
const update = process.argv.includes('--update');

// Discovery surfaces the Python package does not carry: clap's own help rendering, and
// two static documents that live in the binary. Excluded by name rather than diffed,
// because ~350 lines of help text would bury the parity content this artifact exists to
// show. Each entry is a decision; growth in this list is a regression worth arguing over.
const DECLINED = [
  'A Bare Invocation Is Safe and Shows the Complete Contract',
  'The Portable Skill Is Complete and Version-Pinned',
  'Unknown Options Are Usage Errors on Stderr',
];

// The surface must be the built wheel, never python/fdu/ in the working tree: a shim
// importing the source directly would pass while the built package was broken, which is
// the failure public_smoke already exists to prevent. .venv-smoke is exactly such an
// install and make check has just made one, so the gate does not pay for a third wheel
// build; .venv-parity is the standalone path.
const CANDIDATES = ['.venv-parity', '.venv-smoke'];
const python = CANDIDATES.map((v) => join(root, 'crates', 'fdu-py', v, 'bin', 'python')).find(
  (candidate) => existsSync(candidate),
);
if (!python) {
  console.error('run-parity: no interpreter with the fdu wheel installed');
  console.error(`run-parity: looked for ${CANDIDATES.join(', ')} under crates/fdu-py`);
  console.error('run-parity: build one with `make parity-venv`');
  process.exit(2);
}

const filter = `^(?!(${DECLINED.map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})$).*`;

// The performance footer is a recorded gap, not a parity failure: it reports walk
// telemetry the report schema deliberately excludes, so a Report does not carry the
// counts behind it and the Python surface cannot print it. Left in place it fails 44
// sessions and buries the artifact under whole re-printed blocks, which is the opposite
// of an artifact a reviewer can read top to bottom. So the parity corpus is the same
// sessions with that one line dropped from the expectations, generated per run and
// never committed. Everything else is compared exactly.
const corpus = join(root, 'tests', 'parity', '.corpus');
rmSync(corpus, { recursive: true, force: true });
mkdirSync(corpus, { recursive: true });
for (const entry of readdirSync(golden)) {
  const from = join(golden, entry);
  if (entry.endsWith('.tryscript.md')) {
    const text = readFileSync(from, 'utf8')
      .split('\n')
      .filter((line) => !line.startsWith('Performance: '))
      .join('\n');
    writeFileSync(join(corpus, entry), text);
  } else if (statSync(from).isDirectory()) {
    // fixtures/ and bin/ are resolved relative to the session file.
    symlinkSync(from, join(corpus, entry), 'dir');
  }
}
const runner = join(root, 'scripts', 'run-golden.mjs');
const result = spawnSync(process.execPath, [runner, '--filter', filter, '--no-diff'], {
  cwd: root,
  encoding: 'utf8',
  env: { ...process.env, FDU_SURFACE: 'python', FDU_PYTHON: python, FDU_CORPUS: corpus },
});

const output = `${result.stdout ?? ''}${result.stderr ?? ''}`;

// Re-run failures with diffs so the artifact carries the actual differing lines.
const detailed = spawnSync(process.execPath, [runner, '--filter', filter], {
  cwd: root,
  encoding: 'utf8',
  env: { ...process.env, FDU_SURFACE: 'python', FDU_PYTHON: python, FDU_CORPUS: corpus },
});

const HEADER = `# Deviations: the Python surface against the Rust CLI's recorded output
#
# Generated by \`make parity-update\`. Reviewed like any golden.
#
# The golden corpus is NOT duplicated. tests/golden/*.tryscript.md stays exactly as it
# is -- the Rust CLI's output. This file records only what differs when the same
# sessions run against tests/parity/py/fdu, which serves them through the public Python
# package alone.
#
# It is non-empty by construction, and that is the point: an empty result would mean the
# shim never ran, which a naive parity harness reports as success.
#
# Reading it:
#   a session marked ✓   parity holds for that session
#   a session marked ✗   the surfaces differ; the hunk shows how
#     -line               what the Rust CLI produced
#     +line               what the Python surface produced
#
# One difference is deliberate: --version names the surface, so the shim can never be
# mistaken for the binary. Every other ✗ is a tracked gap in the Python API, not an
# accepted difference, and each has a bead:
#
#   fdu-1kw3  cache status and watch records have no renderer  (16 sessions)
#   fdu-gw5b  the binding's copy of the 'full' diagnostic drifted
#   fdu-jozr  list grammar (duplicates, empty entries) is not exposed
#
# The performance footer is excluded from comparison rather than recorded here: it
# reports walk telemetry the report schema deliberately excludes, so the Python surface
# cannot print it, and left in it failed 44 sessions and buried everything else.
#
# This file shrinks as the API closes. Extra hunks mean drift; missing hunks mean a gap
# was fixed and the file should be re-recorded so the change is visible in review.

`;

const observed = HEADER + normalise(`${detailed.stdout ?? ''}${detailed.stderr ?? ''}`);

if (observed.slice(HEADER.length).trim().length === 0) {
  console.error('run-parity: the corpus produced no differences at all.');
  console.error('run-parity: that means the Python shim never ran -- a fallthrough, or');
  console.error('run-parity: the wrong binary. The shim names itself in --version, so a');
  console.error('run-parity: genuine parity run always differs by at least that line.');
  process.exit(1);
}

if (update) {
  writeFileSync(artifact, observed);
  console.log(`run-parity: wrote ${artifact}`);
  process.exit(0);
}

if (!existsSync(artifact)) {
  console.error(`run-parity: no committed artifact at ${artifact}`);
  console.error('run-parity: create it with `make parity-update` and review it');
  process.exit(1);
}

const expected = readFileSync(artifact, 'utf8');
if (expected === observed) {
  const hunks = observed.split('\n').filter((l) => l.startsWith('  ✗')).length;
  console.log(`run-parity: parity holds; ${hunks} recorded deviation(s) matched`);
  process.exit(0);
}

console.error('run-parity: the Python surface differs from its recorded deviations.');
console.error('run-parity: extra hunks mean the Python surface drifted -- a parity bug.');
console.error('run-parity: missing hunks mean a known deviation was fixed; re-record it');
console.error('run-parity: with `make parity-update` so the change is visible in review.\n');
for (const line of diffLines(expected, observed)) {
  console.error(line);
}
process.exit(1);

// Strip what varies between any two runs, so the artifact records parity and nothing
// else. Timings, temporary sandbox paths, and the run's own summary line are noise.
function normalise(text) {
  return text
    .replace(/\\/g, '/')
    .replace(/[^\s'"]*\/(tryscript|fdu)-[A-Za-z0-9._-]+/g, '[SANDBOX]')
    .replace(/[0-9a-f]{16}\.fdu/g, '[HASH].fdu')
    .replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z/g, '[RFC3339]')
    .replace(/("(?:newest_)?mtime_ns":\s*)\d+/g, '$1[MTIME_NS]')
    .replace(/\b\d+(\.\d+)?\s?(ns|µs|ms|s)\b/g, '[TIME]')
    .replace(/^.*\d+ (passed|failed) \([^)]*\)$/gm, '')
    .replace(/^run-golden: .*$/gm, '')
    .replace(/^\s*$\n/gm, '');
}

function diffLines(expected, observed) {
  const a = expected.split('\n');
  const b = observed.split('\n');
  const out = [];
  for (let i = 0; i < Math.max(a.length, b.length); i += 1) {
    if (a[i] !== b[i]) {
      if (a[i] !== undefined) out.push(`  recorded: ${a[i]}`);
      if (b[i] !== undefined) out.push(`  observed: ${b[i]}`);
    }
  }
  return out.slice(0, 60);
}
